### ISSUE TITLE
Сразу после установки Unknown Property – yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by xRayDev** [skeeks-cms/app-basic#1]
Сразу после установки и заливки дампа базы получаю ошибку
Unknown Property – yii\base\UnknownPropertyException 
Getting unknown property: yii\web\Application::admin

Кусок из дебаг-лога:
```
Stack trace:
#0 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\di\ServiceLocator.php(73): yii\base\Component->__get('admin')
#1 E:\opensrv\domains\skeekscms.dd\vendor\skeeks\cms-admin\controllers\AdminController.php(141): yii\di\ServiceLocator->__get('admin')
#2 E:\opensrv\domains\skeekscms.dd\vendor\skeeks\cms-admin\controllers\AdminModelEditorController.php(223): skeeks\cms\modules\admin\controllers\AdminController->init()
#3 E:\opensrv\domains\skeekscms.dd\vendor\skeeks\cms\controllers\AdminTreeController.php(49): skeeks\cms\modules\admin\controllers\AdminModelEditorController->init()
#4 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Object.php(107): skeeks\cms\controllers\AdminTreeController->init()
#5 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Controller.php(84): yii\base\Object->__construct(Array)
#6 [internal function]: yii\base\Controller->__construct('admin-tree', Object(skeeks\cms\Module), Array)
#7 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\di\Container.php(373): ReflectionClass->newInstanceArgs(Array)
#8 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\di\Container.php(154): yii\di\Container->build('skeeks\\cms\\cont...', Array, Array)
#9 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\BaseYii.php(340): yii\di\Container->get('skeeks\\cms\\cont...', Array)
#10 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(567): yii\BaseYii::createObject('skeeks\\cms\\cont...', Array)
#11 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(520): yii\base\Module->createControllerByID('admin-tree')
#12 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(512): yii\base\Module->createController('admin-tree')
#13 E:\opensrv\domains\skeekscms.dd\vendor\skeeks\cms\controllers\TreeController.php(34): yii\base\Module->createController('cms/admin-tree')
#14 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Object.php(107): skeeks\cms\controllers\TreeController->init()
#15 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Controller.php(84): yii\base\Object->__construct(Array)
#16 [internal function]: yii\base\Controller->__construct('tree', Object(skeeks\cms\Module), Array)
#17 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\di\Container.php(373): ReflectionClass->newInstanceArgs(Array)
#18 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\di\Container.php(154): yii\di\Container->build('skeeks\\cms\\cont...', Array, Array)
#19 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\BaseYii.php(340): yii\di\Container->get('skeeks\\cms\\cont...', Array)
#20 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(567): yii\BaseYii::createObject('skeeks\\cms\\cont...', Array)
#21 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(520): yii\base\Module->createControllerByID('tree')
#22 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(512): yii\base\Module->createController('tree/view')
#23 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Module.php(448): yii\base\Module->createController('cms/tree/view')
#24 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\web\Application.php(87): yii\base\Module->runAction('cms/tree/view', Array)
#25 E:\opensrv\domains\skeekscms.dd\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#26 E:\opensrv\domains\skeekscms.dd\vendor\skeeks\cms\app-web.php(23): yii\base\Application->run()
#27 E:\opensrv\domains\skeekscms.dd\frontend\web\index.php(45): include('E:\\opensrv\\doma...')
```

Я так понимаю надо дамп базы новее чем db__2016-08-26_11_09_07.sql или нет?
Устанавливал по инструкции https://docs.cms.skeeks.com/en/latest/overview.html#installation-composer
А дамп базы залил просто в самом phpMyAdmin.

**Comment by skeeks-semenov** [comment]
@xRayDev а с залитым дампом заработало?

**Comment by xRayDev** [comment]
@skeeks-semenov Нет
А есть дамп новее?

**Comment by xRayDev** [comment]
@skeeks-semenov
Судя по composer.lock при composer install ставится skeeks/cms 3.0.1.8 и дамп в backup/db__2016-08-26_11_09_07.sql по дате релиза совпадает с skeeks/cms 3.0.1.8

Куда копать что бы завести демку? Скриншот с окном ошибки закинуть?

**Comment by xRayDev** [comment]
@skeeks-semenov
Вот скриншот с ошибкой

![image 2](https://cloud.githubusercontent.com/assets/437042/23405667/60f75a04-fdcc-11e6-80ff-13742bfeeb2c.png)
![image 3](https://cloud.githubusercontent.com/assets/437042/23405669/64fbd9ea-fdcc-11e6-8fcd-207b99f75b4b.png)
![image 4](https://cloud.githubusercontent.com/assets/437042/23405672/672c3868-fdcc-11e6-8814-b0a4a8392e9e.png)
![image 5](https://cloud.githubusercontent.com/assets/437042/23405675/695c7df0-fdcc-11e6-8bc3-9a36564c0956.png)

И файл дебаг-лога 
[58b56de34b0c7.zip](https://github.com/skeeks-cms/app-basic/files/806799/58b56de34b0c7.zip)

**Comment by skeeks-semenov** [comment]
@xRayDev 
Обновлю этот проект.
Попробуй или использовать:
`COMPOSER_HOME=.composer php composer.phar create-project --no-install --prefer-dist skeeks/app-basic:dev-master example.com`

Или поставить этот проект, его только сегодня собрал:
https://github.com/skeeks-cms/app-shop-smarty

**Comment by skeeks-semenov** [comment]
@xRayDev  Обновил проект, можно попробовать еще разок.

**Comment by xRayDev** [comment]
Попробовал обновленный проект. Получил эту же ошибку.
Не пойму почему он не находит метод setadmin?

**Comment by xRayDev** [comment]
На последнем шаге устуановки композером в консоль пишет так:
```
Generating optimized autoload files
> skeeks\cms\console\Composer::postInstall
```
Это я ставлю на Windows на Open-server c PHP 5.6.

А когда ставил на linux ставил там точно после этих строк еще строки были.
Может в этом дело?

**Comment by skeeks-semenov** [comment]
Видимо да, надо потестировать установку на windows. Сам не ставил.

**Comment by xRayDev** [comment]
На ubuntu поставился и запустился без ошибок.
А на Windows нет вот этой стадии при установке:
```
Generating optimized autoload files
> skeeks\cms\console\Composer::postInstall
        postInstall
                tmp web config is generated
                tmp console config is generated
```
